spring:
  application:
    name: main-service

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:5776/eureka

service:
  tracing:
    otl:
      enabled: true
      endpoint: http://localhost:4317
      traces:
        probability: 1.0
        propagation: tracecontext,baggage

logging:
  level:
    root: info