spring:
  application:
    name: main-service

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka:5776/eureka

logging:
  level:
    root: info