version: '3.8'
name: open-telemetry-test
services:

  postgres:
    container_name: postgres
    image: postgres:13.0-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  solr:
    container_name: solr
    image: solr:latest
    ports:
      - "8983:8983"
    command:
      - solr-precreate
      - item
    environment:
      - APPLICATIONINSIGHTS_CONNECTION_STRING=<Your connection string>
    volumes:
      - ./solr/volume/config/:/etc/default/
      - ./solr/volume/lib/:/opt/trace/
#      - ./solr/volume/lib/applicationinsights.json:/opt/trace/applicationinsights.json

  eureka:
    container_name: eureka
    build:
      context: ./../eureka
      dockerfile: Dockerfile
    ports:
      - "5776:5776"
    environment:
      SERVER_PORT: "5776"

  item-service:
    container_name: item-service
    build:
      context: ./../item-service
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    depends_on:
      - eureka
      - postgres
      - solr

  main-service:
    container_name: main-service
    build:
      context: ./../main-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5006:5006"
    depends_on:
    - eureka
    - solr
    - item-service