spring:
  application:
    name: item-service
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    driverClassName: org.postgresql.Driver
    username: admin
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
  liquibase:
    default-schema: public
    change-log: db/changelog-master.xml

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:5776/eureka

logging:
  level:
    com:
      krokoq: DEBUG